### ISSUE TITLE
No `done` Message for Immediately Filled Orders

### ISSUE THREAD

**Issue by chris-rr** [tardis-dev/mango-bowl#5]
Hi @thaaddeus, something else I've noticed in generated messages for mango-bowl - when an order is opened on the book, and then later traded for its full value, a `done` message with `reason:filled` is generated; however, if an order is placed and filled completely immediately as taker, no `done : filled` message is generated.

This is in contradiction to the serum-vial case, where `done : filled` message is generated regardless of whether filled as maker or taker.  I would expect that a `done` message should be generated; this is the case in CEX exchange L3 streams, and it is important to have an indication among the data when an order no longer has any possibility of participating in activity.

**Comment by thaaddeus** [comment]
Serum and Mango work bit differently on-chain hence differences, I'll have some time later this month hopefully to look into both of your issues.

**Comment by thaaddeus** [comment]
handled in https://github.com/tardis-dev/mango-bowl/commit/8869335a43623ce08e163066635b43fc86aca652
