### ISSUE TITLE
Latency "timestamp" field and client receive timestamp

### ISSUE THREAD

**Issue by diweij** [tardis-dev/mango-bowl#7]
Hi^^ we're using mango-bowl socket for best bid/ask data, and we're trying to measure the latency of data freshness. We use the "timestamp" field from web socket response, and log the time when we receive it. Upon initial connection, the latency is 200-300ms which is understandable, but later it increased to a few seconds all the way to >15 seconds, any idea why? How can we work around it?

I'm running consumer on my local and mango-bowl on my local as well.

**Comment by thaaddeus** [comment]
Not sure, could to slow machine? What machine you're running it one? Have you compared it with hosted mango-bowl (wss://api.mango-bowl.com/v1/ws)?

**Comment by diweij** [comment]
I found out the reason there was some issue when i subscribe to web socket, thank you!
