### ISSUE TITLE
using my own rpc api endpoint in mango-bowl

### ISSUE THREAD

**Issue by diweij** [tardis-dev/mango-bowl#9]
Hi @thaaddeus ^^, I am using quicknode when starting mango-bowl on my local, command I used:
`npx mango-bowl --endpoint 'quick_nod_api_link' --commitment processed --port 8010
`
The rpc api is solana mainnet

I'm subscribing to sol-perp data, but terminal prints out lots of errors:

<img width="1054" alt="Screen Shot 2022-03-09 at 3 23 33 PM" src="https://user-images.githubusercontent.com/5014113/157556004-ef44fed2-334c-4601-a1f3-fb55560d9b87.png">

However I'm able to consume sol-perp, the continuing error message don't seem right, is it because I didn't set up rpc node or is it some tuning i need to do in mango-bowl code? thanks a lot!!

**Comment by thaaddeus** [comment]
it looks like your Solana RPC endpoint has disabled some of the RPC methods that are required for mango-bowl.

**Comment by diweij** [comment]
@thaaddeus is there a way I can select only a few perp to listen to ? eg: only sol-perp and eth-perp

**Comment by thaaddeus** [comment]
it's no possible currently unfortunately
